// generated by stringer -type Sex .; DO NOT EDIT

package gimei

import "fmt"

const _Sex_name = "MaleFemale"

var _Sex_index = [...]uint8{0, 4, 10}

func (i Sex) String() string {
	if i < 0 || i+1 >= Sex(len(_Sex_index)) {
		return fmt.Sprintf("Sex(%d)", i)
	}
	return _Sex_name[_Sex_index[i]:_Sex_index[i+1]]
}
